### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by obiwanjacobi** [huajitech/UnmanagedExports#1]
I was looking for DllExport support for dotnet Core and by the looks of it you support .net standard 2.0.

I've added your nuget package (version 1.0.2) to my test project created a simple static export function and build. 

```csharp
using HuajiTech.UnmanagedExports;
using System;

    public static class Class1
    {
        [DllExport]
        public static IntPtr MyExport()
        {
            return IntPtr.Zero;
        }
    }
````

The resulting assembly (at `bin\Debug\netcoreapp3.1`) does not have any unmanaged exports.
My guess is that 'something' has to run during/after build to rewrite the IL in the assembly and make the function an unmanaged export. That does not seem to happen - there is nothing in the output window to indicate that.

So my question is: what do I need to get this to work?
Thanks

**Comment by funnysyc** [comment]
The `HuajiTech.UnmanageExports.Metadata` package is really just metadata and doesn't do anything. The  `HuajiTech.UnmanageExports.MSBuild` package is the one that actually does the trick.

The `MSBuild` package provides a MSBuild task, add the following MSBuild target to your project so that it runs the task after build.

```xml
<Target Name="Export" AfterTargets="Build">
    <UnmanagedExport File="$(TargetPath)" />
</Target>
```

For .NET Core, it does export the methods, but there's another 'something' to be done, otherwise the assembly will be loaded into .NET Framework, and the CLR raises exceptions when calling the exported methods. (Maybe it works just fine on non-Windows systems.)
I haven't made this work on .NET Core yet, but I guess it's related to `runtimeconfig.json`.

**Comment by obiwanjacobi** [comment]
Got it. 
- The `HuajiTech.UnmanagedExports.MSBuild` is a prerelease (at time of writing) v1.0.0-rc2
- Changed the path macro in the build 'Export' target to `$(TargetPath)`

I now have exports. Will check if/how it runs in .NET Core later.

**Comment by obiwanjacobi** [comment]
I am trying to load the resulting Assembly into a native host on Windows (::LoadLibrary), which fails with an 'invalid image' error.

Not sure this can even be done.

I have successfully loaded mixed C++/CLI assemblies into native hosts (ijwhost.dll) but I can find no references on this scenario I am trying now. 

Do you have any information on this?

**Comment by obiwanjacobi** [comment]
Looks like it is not possible: https://github.com/dotnet/runtime/issues/12611

**Comment by AaronRobinsonMSFT** [comment]
@obiwanjacobi You might want to check out https://github.com/AaronRobinsonMSFT/DNNE.
